apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: nginx
    - image: nginx
    - name: redis
    - image: redis
    - name: memcached
    - image: memcashed
    - name: consul
    - image: concul