apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - image: busybox
    name: busybox
    args:
    - /bin/sh
    - -c
    - echo "hello"
    resources:
      limits:
        cpu: "200"
        memory: "1Gi"