apiVersion: v1
kind: Secret
metadata:
  name: secret-creds
data:
  username: 
  password: TXlTZWN1cmVQYXNz

---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-pod
    image: redis
    volumeMounts:
    - name: secret-creds
      mountPath: /app-creds
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: secret-creds
      